"use strict";

// Generated by CoffeeScript 2.0.3
var bb, gg, input1, input2, mousePressed, rr, setPixel, setup, show, showNumbers, slider, sliderchange;

slider = 0;

input1 = 0;

input2 = 0;

rr = 0;

gg = 0;

bb = 0;

setup = function setup() {
  var canvas;
  canvas = createCanvas(512, 256);
  canvas.position(20, 20);
  pixelDensity(1);
  slider = createSlider(0, 255, 0);
  slider.position(20, 285);
  slider.input(sliderchange);
  slider.size(512, 20);
  input1 = createInput();
  input1.position(20, 320);
  input1.size(256, 20);
  input2 = createInput();
  input2.position(256 + 20, 320);
  input2.size(256, 20);
  sc();
  return show();
};

mousePressed = function mousePressed() {
  if (0 <= mouseX && mouseX < 256 && 0 <= mouseY && mouseY < 256) {
    rr = mouseX;
    gg = mouseY;
    return showNumbers();
  }
};

sliderchange = function sliderchange() {
  bb = slider.value();
  return show();
};

show = function show() {
  var g, k, l, r;
  loadPixels();
  for (r = k = 0; k <= 256; r = ++k) {
    for (g = l = 0; l <= 256; g = ++l) {
      setPixel(r, g);
    }
  }
  updatePixels();
  return showNumbers();
};

showNumbers = function showNumbers() {
  input1.value(nf(rr / 255, 1, 3) + ", " + nf(gg / 255, 1, 3) + ", " + nf(bb / 255, 1, 3));
  input2.value(rr + ", " + gg + ", " + bb);
  fill(rr, gg, bb);
  return rect(256, 0, 256, 256);
};

setPixel = function setPixel(i, j) {
  var index;
  index = 4 * (j * 512 + i);
  pixels[index + 0] = i;
  pixels[index + 1] = j;
  pixels[index + 2] = bb;
  return pixels[index + 3] = 255;
};
//# sourceMappingURL=sketch.js.map
